# Generated by Django 3.2 on 2023-04-06 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEquations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_symbol', models.TextField()),
                ('latex', models.TextField(blank=True, null=True)),
                ('view', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathematicalEquations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latex_define', models.TextField()),
                ('view', models.TextField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('type_equations', models.CharField(blank=True, choices=[('0', 'Default'), ('1', 'Sophomore'), ('2', 'Junior')], default='0', max_length=2)),
                ('grade_school', models.CharField(blank=True, choices=[('0', 'Default'), ('1', 'Sophomore'), ('2', 'Junior')], default='0', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('list_code', models.ManyToManyField(through='system.CharacterEquations', to='system.CharacterRelationship')),
            ],
        ),
        migrations.AddField(
            model_name='characterequations',
            name='character_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.characterrelationship'),
        ),
        migrations.AddField(
            model_name='characterequations',
            name='mathematical_equations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.mathematicalequations'),
        ),
    ]
