version: '3.9'

services:

  imatpro_backend:
    build:
      context: /Users/system01/Documents/repository/python/backend_imatpro_system
      dockerfile: /Users/system01/Documents/repository/python/backend_imatpro_system/docker/work/backend/Dockerfile
    container_name: imatpro_backend_local
    image: imatpro_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    expose:
        - 8000
    ports:
      - 8000:8000
    env_file:
      - /Users/system01/Documents/repository/python/backend_imatpro_system/config/.env.local

