# Generated by Django 4.2.3 on 2023-09-22 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view_text', models.CharField(max_length=50, null=True, verbose_name='character')),
                ('view_latex', models.CharField(max_length=50, unique=True, verbose_name='latex')),
                ('view', models.CharField(blank=True, max_length=250, null=True, verbose_name='view')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='active')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view', models.CharField(max_length=250, null=True, verbose_name='equation')),
                ('latex_define', models.CharField(max_length=250, null=True, verbose_name='latex')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('type_representation', models.CharField(max_length=30, null=True, verbose_name='type')),
                ('solution_id', models.UUIDField(blank=True, null=True, verbose_name='solution')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='order')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeSchool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Required. 5 characters or fewer. letters and digits', max_length=5, unique=True, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeEquation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Required. 5 characters or fewer. letters and digits', max_length=5, unique=True, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RepresentationEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.character', verbose_name='Character')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.equation', verbose_name='Equation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='equation',
            name='grade_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_school', to='mathematical.gradeschool', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='equation',
            name='list_code',
            field=models.ManyToManyField(through='mathematical.RepresentationEquation', to='mathematical.character'),
        ),
        migrations.AddField(
            model_name='equation',
            name='type_equations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_equations', to='mathematical.typeequation', verbose_name='Equation'),
        ),
    ]
