# Generated by Django 3.2 on 2023-07-20 20:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view_text', models.TextField(blank=True, null=True, verbose_name='CHARACTER')),
                ('view_latex', models.TextField(unique=True, verbose_name='LATEX')),
                ('view', models.TextField(blank=True, null=True, verbose_name='VIEW')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='DESCRIPTION')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view', models.TextField(blank=True, null=True, verbose_name='EQUATION')),
                ('latex_define', models.TextField(blank=True, null=True, verbose_name='LATEX')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='DESCRIPTION')),
                ('type_representation', models.TextField(blank=True, null=True, verbose_name='TYPE')),
                ('solution_id', models.UUIDField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeSchool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=5, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='DEGREE SCHOOL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=5, unique=True, verbose_name='ID')),
                ('name', models.TextField(max_length=30, unique=True, verbose_name='DEGREE EQUATION')),
                ('description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentationEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='ORDER')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.character', verbose_name='CHARACTER')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.equation', verbose_name='EQUATION')),
            ],
        ),
        migrations.AddField(
            model_name='equation',
            name='grade_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_school', to='mathematical.gradeschool', verbose_name='DEGREE SCHOOL'),
        ),
        migrations.AddField(
            model_name='equation',
            name='list_code',
            field=models.ManyToManyField(through='mathematical.RepresentationEquation', to='mathematical.Character'),
        ),
        migrations.AddField(
            model_name='equation',
            name='type_equations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_equations', to='mathematical.typeequation', verbose_name='DEGREE EQUATION'),
        ),
    ]
