# Generated by Django 3.2 on 2023-07-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematical', '0002_auto_20230715_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeequation',
            name='value',
            field=models.TextField(max_length=5, unique=True, verbose_name='fffff'),
        ),
    ]
