# Generated by Django 3.2 on 2023-03-30 04:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEquations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('typeSymbol', models.TextField()),
                ('latex', models.TextField()),
                ('view', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('lastUpdate', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathematicalEquations',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('latexDefine', models.TextField()),
                ('view', models.TextField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('typeEquations', models.CharField(blank=True, choices=[('AA', 'EQUATION1'), ('EE', 'EQUATION2')], max_length=2)),
                ('gradeSchool', models.CharField(blank=True, choices=[('AAA', 'SCHOOL'), ('EEE', 'SCHOOL2'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=3)),
                ('date', models.DateField(default=datetime.date.today)),
                ('lastUpdate', models.DateField(blank=True)),
                ('listCode', models.ManyToManyField(through='equation.CharacterEquations', to='equation.CharacterRelationship')),
            ],
        ),
        migrations.AddField(
            model_name='characterequations',
            name='character_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equation.characterrelationship'),
        ),
        migrations.AddField(
            model_name='characterequations',
            name='mathematical_equations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equation.mathematicalequations'),
        ),
    ]
