# Generated by Django 3.2 on 2023-07-11 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view_text', models.TextField(unique=True)),
                ('view_latex', models.TextField(unique=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('latex_define', models.TextField(blank=True, null=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeSchool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=2)),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=2, unique=True)),
                ('name', models.TextField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquationRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField()),
                ('type_representation', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.character')),
                ('equations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematical.equation')),
            ],
        ),
        migrations.AddField(
            model_name='equation',
            name='grade_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_school', to='mathematical.gradeschool'),
        ),
        migrations.AddField(
            model_name='equation',
            name='list_code',
            field=models.ManyToManyField(through='mathematical.EquationRepresentation', to='mathematical.Character'),
        ),
        migrations.AddField(
            model_name='equation',
            name='type_equations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_equations', to='mathematical.typeequation'),
        ),
    ]
